### ISSUE TITLE
MLB Games Endpoint filters broken

### ISSUE THREAD

**Issue by chrishenry** [stattleship/stattleship-api#24]
While attempting to retrieve a single game (via the [stattleship-python lib](https://github.com/stattleship/stattleship-python)), the games endpoint doesn't seem to recognize the game_id query parameter.

For example, this URL, which I would think returns a single game, returns 80.

```
https://api.stattleship.com/baseball/mlb/games?id=mlb-2017-nym-ari-2017-05-15-1840&page=1
```

I've also attempted to send the Stattleship GUID for the game, as well as a few other options.

**Comment by dthyresson** [comment]
Hi, @chrishenry ... yes, that's correct.

We decided not to lookup by uuids as a design principal so `id` and `game_id` aren't the same.

In this case, you'd use `game_id` and the slug friendly value.

I can see that it's a little confusing.

Let me consider sort of "aliasing" id and the slug params in the endpoint requests.

Seems reasonable.

**Comment by chrishenry** [comment]
Hey! Thanks for the quick response.

I was using `id` because that's what the [docs show](http://developers.stattleship.com/#baseball-games), but that's super helpful to know. Is there a way I can submit a PR to fix the docs?

So I've now changed to using `game_id` with the slug of the game, and I'm still seeing 80 results.

```
>>> result = s.ss_get_results(sport='baseball', league='mlb', ep='games', game_id='mlb-2017-nym-ari-2017-05-15-1840')
Making Initial API Request
<Response [200]>
https://api.stattleship.com/baseball/mlb/games?game_id=mlb-2017-nym-ari-2017-05-15-1840&page=1
Stattleship API request complete
>>> len(result[0]['games'])
80
```

Does that make sense to you? Do I still have it wrong? (There's a really good chance I do 😉)
