### ISSUE TITLE
[Enhancement] Additional MLB stats

### ISSUE THREAD

**Issue by phil-andrews** [stattleship/stattleship-api#25]
Since this is backboned off of SportsRadar is it possible to pull in these addtional MLB player profile stats? 

career ballpark whip
career ballpark era
career vs opp whip
career vs opp era
Day/night whip
day/night era
day/night run support

**Comment by dthyresson** [comment]
Hi @phil-andrews I couldn't find those stats on https://developer.sportradar.com/files/indexBaseball.html#team-rosters-active. Note: we still use the v5 of the API.

I think you might be looking at the Splits endpoint data: https://developer.sportradar.com/files/indexBaseball.html#seasonal-splits46

That's info we don't fetch yet. But I'll mark as an enhancement.
