### ISSUE TITLE
NFL Preseason scoring_plays data missing

### ISSUE THREAD

**Issue by craig-cogdill** [stattleship/stattleship-api#26]
The `scoring_plays` endpoint doesn't return any scoring data for the NFL Preseason years 2016-2017 or 2017-2018 (current). 

Example URI:
`https://api.stattleship.com/football/nfl/scoring_plays?interval_type=preseason&season_id=nfl-2016-2017`

Querying `scoring_plays` returns valid data for preseasons before 2016-2017 with the `interval_type=preseasonweek` parameter.

Could it be related to the `preseasonweek`/`preseason` keyword changeover?

**EDIT**: Now that I am playing with the API a bit more, unless I am misunderstanding the docs, getting the scoring plays by a `game_id` is just not working in general.

Example URI:
`https://api.stattleship.com/football/nfl/scoring_plays?game_id=nfl-2016-2017-oak-den-2017-01-1-1625`

Output from above request:
{"scoring_plays":[]}

**Comment by dthyresson** [comment]
@craig-cogdill I'll look into this tonight and see if it is related to the `interval_type` or just because sometimes not all stats are provided during the preseason -- or some other issue. 

Scenarios I'll try: 2016-2017 preseason game, regularseason game; 2017-2018 preseason games

**Comment by craig-cogdill** [comment]
@dthyresson Sounds good and thanks for the quick reply!

Also, did you see my edit? I am trying to loop through the games and then fetch the scoring plays for that particular game. Does that URI look like it should return that data, or am I missing something? As it stands, I can't seem to get the scoring plays on a per-game basis.

**Comment by dthyresson** [comment]
I was able to fetch scoring plays for 

```https://api.stattleship.com/football/nfl/scoring_plays?season_id=nfl-2016-2017&game_id=nfl-2016-2017-mia-ne-2016-09-18-1300```

Scoring play data seems to be missing for `nfl-2016-2017-oak-den-2017-01-1-1625` which is odd; same for last night's `nfl-2017-2018-sea-lac-2017-08-13-2000`. Am looking into this to see why the data is missing.

Note: there is play by play for last night's Seattle game:

```https://api.stattleship.com/football/nfl/play_by_play/nfl-2017-2018-sea-lac-2017-08-13-2000?include_stats=1&include_advancements=1```

as well as that Denver game you noted:

```https://api.stattleship.com/football/nfl/play_by_play/nfl-2016-2017-oak-den-2017-01-1-1625?include_stats=1&include_advancements=1```

So, looks like a bug in persisting the scoring that I'll dig into.

Thanks for finding this.

**Comment by dthyresson** [comment]
Once I determine the cause, I'll be able to reprocess for the source stats and correct.

**Comment by craig-cogdill** [comment]
Any luck @dthyresson ? I was able to use the play-by-play API as a workaround for gathering scoring plays, but it seems that play-by-play data isn't available prior to the 2016-2017 season. Not sure if that's expected or a separate issue.
