### ISSUE TITLE
Coach info

### ISSUE THREAD

**Issue by b4youleap** [stattleship/stattleship-api#3]
It would be nice to get coach information for the team - name, type of coach, season coached or start/end  dates of coaching job, etc.

**Comment by dthyresson** [comment]
Great idea.

For the NFL, we'll know the coach per team from the raw roster report data.

```
       {
            "name_full": "Bill Belichick",
            "name_last": "Belichick",
        },
        {
            "name_full": "Matt Patricia",
            "position": "Defensive Coordinator",
        },
        {
            "name_full": "Josh McDaniels",
            "position": "Offensive Coordinator",
        }
```
- Coach belongs_to Team and Season
- Get from roster data
- Coach endpoint to return coaches for a team, all coaches for league
- Include coaches on game, just like officials and players (? - though we don't really know they are coaching the game ...)
